services:
  - type: web
    name: root-metodos
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn home:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.7
